[build]
command = "bun run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "thumb-gen"

[services.source]
repo = "Malith-Rukshan/thumb-gen"
branch = "main"

[services.build]
buildCommand = "bun install && bun run build"

[services.deploy]
startCommand = "bun run preview --host 0.0.0.0 --port $PORT"